name:                copycheck
version:             0.3.3.1
github:              "11xx/copycheck"
license:             BSD3
author:              "Lucas Gabriel"
maintainer:          "g@11xx.org"
copyright:           "BSD3"

extra-source-files:
- README.org
- CHANGELOG.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Codeberg at <https://codeberg.org/11xx/copycheck>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.17 && < 1.17.1
- regex-tdfa >= 1.3 && < 1.4
- bytestring >= 0.11 && < 0.12
- filepath-bytestring >= 1.4.2 && < 1.4.3
- rawfilepath >= 1.0 && < 1.1
- utf8-string >= 1.0.2 && < 1.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  copycheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copycheck

tests:
  copycheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copycheck
