# copycheck

# Oct 12 2:57
# first "semi-finished" # [2022-12-22 Thu 22:16:37 -03]

# README initially generated by chatGPT
* =copycheck=: a command-line tool for renaming files with copy identifiers
  :PROPERTIES:
  :CUSTOM_ID: copycheck-a-command-line-tool-for-renaming-files-with-copy-identifiers
  :END:
=copycheck= is a command-line tool that allows the renaming a file to
include a copy identifier if a file with the same name already exists in
a specified directory. This can be useful to keep multiple copies of a
file in the same directory, but need to ensure that each copy has a
unique name.

** Notes
   :PROPERTIES:
   :CUSTOM_ID: notes
   :END:
- This tool doesn't make filesystem changes, it only prints to the
  terminal.
- =copycheck= only works with files, not directories.
- If the =--dir= option is not specified, =copycheck= will use the
  current directory as the target directory.
- If the =--padding= option is not specified, =copycheck= will use a
  default value of 2 padding zeros for the copy identifier, e.g: "=01=".
- If a file with the same name as the renamed file already exists,
  =copycheck= will increment the copy identifier and try again until a
  unique name is found.

# * TODOs                                                                :todo:
# [ ] replace for specified copy text with =-r <copytext-regexp>=
# [2022-12-22 Thu 22:34:01 -03]

** Requirements
   :PROPERTIES:
   :CUSTOM_ID: requirements
   :END:
This program requires the following Haskell libraries:
- =Data.ByteString.UTF8=
- =Data.ByteString.Char8=
- =Options.Applicative=
- =RawFilePath=
- =System.FilePath.Posix.ByteString=
- =Text.Regex.TDFA=

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:
To install =copycheck=, clone this repository and build the executable
using the Haskell tool =stack=:

#+begin_example
  git clone https://codeberg.org/11xx/copycheck
  cd copycheck
  stack install
#+end_example

This will build the executable and copy it to Stack's default
=~/.local/bin=, or the location specified by =local-bin-path:= in Stack's
=config.yaml=. This directory can be added to =PATH= to make the =copycheck=
command available globally.

** Usage
   :PROPERTIES:
   :CUSTOM_ID: usage
   :END:
To use =copycheck=, open a terminal and point it to the directory
containing the file to be renamed. Then, run the =copycheck=
command with the following options:

#+begin_example
  copycheck --file <filename> --text <copy-text> --dir <directory> --padding <num-padding-zeros>
#+end_example

- =--file=: the path to the file to be renamed (required)
- =--text=: the string to be added to the file name to indicate it is a
  copy (optional, defaults to =_COPY_=)
- =--dir=: the directory where the file is located (optional, defaults
  to the current directory)
- =--padding=: the number of padding zeros to be added to the copy
  identifier (optional, default is =2=, producing a number such as "02")

** Example
   :PROPERTIES:
   :CUSTOM_ID: example
   :END:
Here is an example of how =copycheck= might be used to rename a file:

#+begin_example
  copycheck --file "report.txt" --text "_copy" --dir "documents" --padding 3
#+end_example

This will rename the file =report.txt= to =documents/report_copy001.txt=
if a file with that name already exists in the =documents= directory. If
a file with that name does not exist, the original file will not be
renamed.

